accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 

    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

applications/urls.py
from django.urls import path
from . import views

app_name='applications'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.ApplicationList.as_view(), name="all"),
    path("new/", views.CreateApplication.as_view(), name="create"),
    path("by/<username>/",views.UserApplications.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.ApplicationDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeleteApplication.as_view(),name="delete"),

]

resumefilter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
 

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.HomePage.as_view(), name="home"),
    path('about/', views.AboutPage.as_view(), name="about"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('companys/',include("companys.urls", namespace="companys")),
    path('applications/', include("applications.urls", namespace="applications")),
]

applications/models.py
import json
import sys
import time
import requests

# pip install misaka
import misaka

from django.db import models
from django.conf import settings
from django.urls import reverse

from companys.models import Company
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, request
from django.shortcuts import redirect, render
from django.urls.base import reverse_lazy
User = get_user_model()


class Application(models.Model):
    '''
        Application model containing details of the application, along with data base restrictions and constraints
    '''

    user = models.ForeignKey(
        User, related_name="applications", on_delete=models.CASCADE)
    company = models.ForeignKey(
        Company, related_name="applications", null=True, blank=True, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254, unique=True)
    github = models.URLField(max_length=254, blank=True)
    linkedin = models.URLField(max_length=254, blank=True)
    portfolio_site = models.URLField(max_length=254, blank=True)
    resume = models.FileField(upload_to='resume/')
    tell_us_something_about_yourself = models.TextField(
        max_length=150)
    tell_us_about_your_weaknesses = models.TextField(
        max_length=150)
    apart_from_core_technical_skills = models.TextField(
        max_length=150)
    how_do_you_handle_stress_and_Pressure = models.TextField(
        max_length=150)
    do_you_like_to_work_in_a_team_or_work_alone = models.CharField(
        max_length=50)
    What_do_you_prefer_on_weekends_staying_home_or_going_out = models.CharField(
        max_length=50)
    would_you_correct_your_colleagues_or_wont_bother = models.CharField(
        max_length=50)
    in_a_group_which_person_has_your_attention = models.CharField(
        max_length=50)
    do_you_believe_you_can_achieve_everything = models.CharField(
        max_length=50)
    What_attracts_you_science_or_music = models.CharField(
        max_length=50)
    do_you_like_to_plan_before_or_after_things = models.CharField(
        max_length=50)
    would_you_change_your_preferences = models.CharField(
        max_length=50)

    class Meta:
        # How to order application in admin side
        ordering = ['email']

    def __str__(self):
        return f"{self.email}"

    def save(self, *args, **kwargs):
        '''
        Saving application form into the data base, perfoming compute on text messages.
        '''
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # To check information about a particular application
        return reverse(
            "applications:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

applications/forms.py
from django import forms
from . import models


class ApplicationForm(forms.ModelForm):
    '''
        Application form for applying to a company        
    '''
    class Meta:
        # Selecting all the fields
        fields = '__all__'
        model = models.Application

    def __init__(self, *args, **kwargs):
        # Storing information about a user to a company
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["company"].queryset = (
                models.Company.objects.filter(
                    pk__in=user.companys.values_list("company__pk")
                )
            )

applications/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404, HttpResponse
from django.views import generic
from django.views.generic import TemplateView


# pip install django-braces
from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
from . forms import ApplicationForm
from django.shortcuts import render
User = get_user_model()


class ApplicationList(SelectRelatedMixin, generic.ListView):
    '''
    List of all the applications using generic list view
    '''
    model = models.Application
    # Fields to be selected
    select_related = ("user", "company")


class UserApplications(generic.ListView):
    '''
    All the applications filled by the user
    '''
    model = models.Application
    template_name = "applications/user_application_list.html"

    def get_queryset(self):
        # Try to fetch all the applications by a username field
        try:
            self.application_user = User.objects.prefetch_related(
                "applications").get(username__iexact=self.kwargs.get("username"))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.application_user.applications.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["application_user"] = self.application_user
        return context


class ApplicationDetail(SelectRelatedMixin, generic.DetailView):
    '''
    A detailed view of a particular application using Detail View
    '''
    model = models.Application
    select_related = ("user", "company")

    def get_queryset(self):
        # filering the application
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreateApplication(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    '''
    TO create a particular form, the user must be loged in and we use Create view 
    '''

    # Select the model and it's fields
    model = models.Application
    fields = ['user', 'company', 'email', 'github', 'linkedin',
              'portfolio_site', 'resume',
              'tell_us_something_about_yourself', 'tell_us_about_your_weaknesses', 'apart_from_core_technical_skills', 'how_do_you_handle_stress_and_Pressure',
              'do_you_like_to_work_in_a_team_or_work_alone', 'What_do_you_prefer_on_weekends_staying_home_or_going_out', 'would_you_correct_your_colleagues_or_wont_bother', 'in_a_group_which_person_has_your_attention', 'do_you_believe_you_can_achieve_everything', 'What_attracts_you_science_or_music', 'do_you_like_to_plan_before_or_after_things', 'would_you_change_your_preferences'
              ]

    def form_valid(self, form):
        '''
        To validate the fields as well as to save the form
        '''
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeleteApplication(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    '''
    TO delete a particular form, the user must be loged in and we use Create view 
    '''

    # Select the model and it's fields
    model = models.Application
    select_related = ("user", "company")
    success_url = reverse_lazy("applications:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        # delete the application form
        messages.success(self.request, "Application Deleted")
        return super().delete(*args, **kwargs)


class Application_ThanksPage(TemplateView):
    '''
    When the user has logged out of the application
    '''
    template_name = "applications/application_thanks.html"

applications/templates/applications/_application.html
<div class="media">
	<h3 class="mr-5"><a href="{% url 'applications:for_user' username=application.user.username %}">@{{ application.user.username }}</a></h3>
	<!-- User name -->
	<div class="media-body">
		<strong>{{ application.user.username }}</strong>
		<h5>{{ application.email }}</h5>
		<h5>{{ application.message_html|safe }}</h5>
		<!-- To check the time at which application was posted -->
			<time class="time"><a href="{% url 'applications:single' username=application.user.username pk=application.pk %}">{{ application.created_at }}</a></time>
			{% if application.company %}
			<span class="company-name">in <a href="#">{{ application.company.name }}</a></span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and application.user == user and not hide_delete %}
				<br>
			{% endif %}
		</div>
	</div>
</div>

applications/templates/applications/application_base.html
{% extends "base.html" %}

{% block content %}
<div class="card">
	<div class="card-body">
	  	<div class="container">
			<h2 class="text-center">Application page</h2>
			{% block preapplication %}{% endblock %}
			{% block application_content %}{% endblock %}
			{% block post_application %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

applications/templates/applications/application_detail.html
{% extends "applications/application_base.html" %}

{% block post_application %}
<!-- <div class="col-md-8"> -->
    {% include "applications/_application.html" %}
    <br>
<!-- </div> -->
{% endblock %}

applications/templates/applications/application_form.html
{% extends "applications/application_base.html" %}
<!-- exteding application_base.html -->
{% load bootstrap4 %}

<!-- inheriting into application_content -->
{% block application_content %}
<h2>Create New Application</h2>
<form method="POST" action="{% url 'applications:create' %}" id="postForm" enctype ="multipart/form-data">
	{% csrf_token %}
	<!-- For security feature, csrf token is used -->
	{% bootstrap_form form %}

	<div class='question'>
		<div class='question-headline'>
		  1. imagine yourself in between an argument 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-1' type='radio' value='0'><label for="q1a1">you'll say whatver you feel like without hesitating </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-1' type='radio' value='1'><label for="q1a2">you'll stay on your fact and prove it </label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-1' type='radio' value='2'><label for="q1a3">you'll sit down with that person and calmly put your points</label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-1' type='radio' value='3'><label for="q1a4">you'll try to cold down the situation and ignore it </label></input>
	  </div>
		</div>
		</div>
	
		<div class='question'>
		<div class='question-headline'>
		  2. what you like for weekends 
		</div>
		<hr class="line">
		<div class='question-answers'>
		<div class='answer'>
			<input id='q2a1' name='question-2' type='radio' value='0'><label for="q2a1">going out partying with friends </label></input>
		</div>
		<div class='answer'>
			<input id='q2a2' name='question-2' type='radio' value='1'><label for="q2a2">travelling alone </label></input>
		</div>
		<div class='answer'>
			<input id='q2a3' name='question-2' type='radio' value='2'><label for="q2a3">sitting in your appartment and watch tv </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-2' type='radio' value='3'><label for="q1a4">spending time with family and friends </label></input>
	  </div>
		</div>
		</div>
	
	  <div class='question'>
	  <div class='question-headline'>
		3. what would you generally do in an office party 
	  </div>
	  <hr class="line">
	  <div class='question-answers'>
		<div class='answer'>
		  <input id='q3a1' name='question-3' type='radio' value='0'><label for="q3a1">tearinng it up on the dance floor </label></input>
		</div>
		<div class='answer'>
		  <input id='q3a2' name='question-3' type='radio' value='1'><label for="q3a2">you'll try to socialize and get to know new people </label></input>
		</div>
		<div class='answer'>
		  <input id='q3a3' name='question-3' type='radio' value='2'><label for="q3a3">on the side lines observing with a friend </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-3' type='radio' value='3'><label for="q1a4">you would stick to a person you know and focus and food and drinks </label></input>
	  </div>
	  </div>
	  </div>
	
	  <div class='question'>
		<div class='question-headline'>
		  4. what would you do if someone you know is going through a rough patch 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-4' type='radio' value='0'><label for="q1a1">you'll tell them to focus on work and keep constant watch on them </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-4' type='radio' value='1'><label for="q1a2">you'll motivate them and try to help- them in thier work</label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-4' type='radio' value='2'><label for="q1a3">you'll try to cheer them up and distract them with fun things  </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-4' type='radio' value='3'><label for="q1a4">you'll console him even if it's his wrong doing </label></input>
	  </div>
		</div>
		</div>
		  
	  <div class='question'>
		<div class='question-headline'>
		  5. how do you best sleep at night  
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-5' type='radio' value='0'><label for="q1a1">with a little music and a nice cool room </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-5' type='radio' value='1'><label for="q1a2">as long as i'm alone i intend to sleep just fine </label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-5' type='radio' value='2'><label for="q1a3">sleep?what's that </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-5' type='radio' value='3'><label for="q1a4">just turn off the lights </label></input>
	  </div>
		</div>
		</div>
			
	  <div class='question'>
		<div class='question-headline'>
		  6. how positive are you 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-6' type='radio' value='0'><label for="q1a1">i try to spin positively but life gets hard sometimes </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-6' type='radio' value='1'><label for="q1a2">honeslty cynical. not all things are roses and honey </label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-6' type='radio' value='2'><label for="q1a3">i'm always pretty positive </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-6' type='radio' value='3'><label for="q1a4">based on current situation and facts </label></input>
	  </div>
		</div>
		</div>   
		
	  <div class='question'>
		<div class='question-headline'>
		  7. field of interests 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-7' type='radio' value='0'><label for="q1a1">Reading books ,coding and solving puzzles </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-7' type='radio' value='1'><label for="q1a2">music, poetry and writing </label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-7' type='radio' value='2'><label for="q1a3">trekking and exploring </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-7' type='radio' value='3'><label for="q1a4">sports and competitive games </label></input>
	  </div>
		</div>
		</div>
		  
	  <div class='question'>
		<div class='question-headline'>
		  8. are you more of early bird or night owl 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-8' type='radio' value='0'><label for="q1a1">Depend if it's a weekend or not </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-8' type='radio' value='1'><label for="q1a2">a bit of both </label></input>
		</div>
		<div class='answer'>
			<input id='q1a3' name='question-8' type='radio' value='2'><label for="q1a3">Night owl </label></input>
		</div>
		<div class='answer'>
		  <input id='q1a4' name='question-8' type='radio' value='3'><label for="q1a4">Early bird </label></input>
	  </div>
		</div>
		</div>     
			
	  <div class='question'>
		<div class='question-headline'>
		  9. at the end of the day how do you recharge yourself ?
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-9' type='radio' value='0'><label for="q1a1">spending alone time doing my hobbies </label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-9' type='radio' value='1'><label for="q1a2">sitting down with people </label></input>
		</div>
		</div>
		</div>
	
	  <div class='question'>
		<div class='question-headline'>
		  10. would you choose following heart or your thoughts ? 
		</div>
		<hr class="line">
		<div class='question-answers'>
		  <div class='answer'>
			<input id='q1a1' name='question-10' type='radio' value='0'><label for="q1a1">heart is the way</label></input>
		  </div>
		<div class='answer'>
			<input id='q1a2' name='question-10' type='radio' value='1'><label for="q1a2">brain op</label></input>
		</div>
		</div>
		</div>


	{% buttons %}
	<div style="text-align: center">
		<button type="submit" class="btn btn-primary btn-larg vertical-cente">Post</button>
	</div>
	<br>
	{% endbuttons %}
</form>
{% endblock %}

applications/templates/applications/application_thanks.html
{% extends "applications/application_base.html" %}
{% block application_content %}
    
    <div class="jumbotron jumbotron-fluid mb-0">
    <h1>Thanks for filling this application! We will get back to you @{{ application.user.username }}!</h1>
    </div>

{% endblock %}

applications/templates/applications/user_application_list.html
{% extends "applications/application_base.html" %}
{% load humanize %}

{% block pre_post_application %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Companies</h5>
			<ul class="list-unstyled">

				{% for member_company in get_user_companys %}
				<li class="company li-with-bullet">
					<a href="{% url 'companys:single' slug=member_company.company.slug %}">{{ member_company.company.name }}</a>
				</li>
				{% endfor %}

			</ul>
			<br>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Companies</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %} #}
				{% for other_company in get_other_companys %}
					<li class="company li-with-bullet"><a href="{% url 'companys:single' slug=other_company.slug %}">{{ other_company.name }}</a></li>
				{% endfor %}
			</ul>
			<br>
		</div>
	</div>
</div>
{% endblock %}
{% block post_application %}
<div class="col-md-8">
	{% for application in application_list %}
  {% include "applications/_application.html" %}
	{% endfor %}
	<br>
</div>
{% endblock %}