accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 

    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

companys/urls.py
from django.urls import path
from . import views

app_name = 'companys'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.ListCompanys.as_view(), name="all"),
    path("new/", views.CreateCompany.as_view(), name="create"),
    path("applications/in/<slug>/",views.SingleCompany.as_view(),name="single"),
    path("join/<slug>/",views.JoinCompany.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveCompany.as_view(),name="leave"),
]

resumefilter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
 

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.HomePage.as_view(), name="home"),
    path('about/', views.AboutPage.as_view(), name="about"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('companys/',include("companys.urls", namespace="companys")),
    path('applications/', include("applications.urls", namespace="applications")),
]

templates/about.html
{% extends "base.html" %}
{% block content %}
<!-- inherting to base.html file -->
<title>About us</title>
<section id="sec-about" class="">
  <div class="card">
    <div class="card-body">
        <div class="information" style="padding: 10px;">
          <div class="row justify-content-center text-center">
            <div class="col-md-10 col-lg-8">
              <h1 style="text-align:center">About project</h1>
              <hr>
              <p class="mt-4 mb-4">Our application aims to take personality and sentiment during the resume filtration process. 
                The ultimate motive is to provide a better experience for our intended audience.
                Our project will only be implemented as a software and will have no extra hardware needed.
                </p>
              <img src="https://files.realpython.com/media/The-Ultimate-Guide-To-Speech-Recognition-With-Python_Watermarked.c0511baf27ba.jpg" alt="An image analysis pic" style="width:500px;height:300px;"/>
            </div>
          </div>
          <br>
          <!-- Working of voice analysis API -->
          <h3>The Personality prediction API</h3>
          <ol>   
              <li>Input: Takes String as an Input inside a JSON package.</li>
              <li>Output: Returns Personality predicted as a String inside a JSON package.</li>
          </ol>
          <br>

          <h3>The Sentiment prediction API</h3>
          <ol>   
              <li>Input: Takes String as an Input inside a JSON package.</li>
              <li>Output: Returns Sentiment predicted as a String inside a JSON package.</li>
    
          </ol>
        </div>
      </div>
    </div>
</section>
    
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<!-- Used to enable loading static files inside HTML in Django framework -->
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <!-- Api's href for CSS, fonts and bootstrap -->
  <meta name="viewport" content="width=device-width, initial-scale=1"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css'>
  <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
  <link rel=”stylesheet” href="{% static 'css/master.css' %}" type="text/css" >
  <title>Resume Filter</title>

</head>
<style>
  body, html {
margin: 0;
font-family: Roboto, Arial, helvetica, sans-serif;
}

a {
outline: none;
}

.navbar-container {
text-align: center;
background-color: #009688;
box-shadow: 0px -20px 5px 20px #333333;
padding: 10px;
font-size: 0;
}

.navbar-container ul {
margin: 0;
padding: 0;
text-align: right;
display: inline-block;
vertical-align: middle;
}

.navbar-container ul li {
display: inline-block;
font-size: 16px;
}

.navbar-container ul li a {
color: #ffffff;
text-decoration: none;
display: inline-block;	
padding: 10px;
transition: color 0.5s;
}

.navbar-container ul li .underline {
height: 3px;
background-color: transparent;
width: 0%;
transition: width 0.2s, background-color 0.5s;
margin: 0 auto;
}

.navbar-container ul li.active-link .underline {
width: 100%;
background-color: white;
}

.navbar-container ul li:hover .underline {
background-color: white;
width: 100%;
}


.navbar-container ul li:active a {
transition: none;
color: rgba(255,255,255,0.76);
}

.navbar-container ul li:active .underline {
transition: none;
background-color: rgba(255,255,255,0.76);
}
.card-container{
background-color: #ffc8dd;
margin-right: 120px;
margin-left: 120px;
margin-top: 70px;
margin-bottom: 70px;
}
.footer {
position: relative;
margin-top: 45px;
}

.footer .container-fluid {
padding: 60px 0 0 0;
}

.footer .footer-info {
position: relative;
width: 100%;
text-align: center;
}

.footer .footer-info h2 {
margin-bottom: 20px;
font-size: 18px;
font-weight: 700;
color: #000;
}

.footer .footer-info h3 {
margin-bottom: 25px;
font-size: 14px;
font-weight: 600;
color: #000;
}

.footer .footer-menu {
width: 100%;
display: flex;
justify-content: center;
}

.footer .footer-menu p {
color: #ffafcc;
font-size: 12px;
font-weight: 600;
line-height: 20px;
padding: 0 15px;
border-right: 1px solid rgb(26, 23, 23);
}

.footer .footer-menu p:last-child {
border: none;
}

</style>

<!-- Creating a Navbar using HTML and CSS -->
<div class="wrapper" >
  <section class="hero">
    <header>
      <div class="container">
        <nav class="navbar navbar-light navbar-toggleable-sm" style="background-color: #CEEDF8; ">
          <a class="navbar-brand mb-0" href="{% url 'home' %}" class="btn btn-simple">Resume Filter</a>

          <div id="headerNav" class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <div class="navbar-nav ml-auto">
                <!-- Having different navbar, if the user is authenticated -->
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'home' %}" class="btn btn-simple">Home</a>
                  <a class="nav-item nav-link" href="{% url 'about' %}" class="btn btn-simple">About</a>
                  <a class="nav-item nav-link" href="{% url 'companys:all' %}" class="btn btn-simple">Companies</a>
                  <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'home' %}" class="btn btn-simple">Home</a>
                  <a class="nav-item nav-link" href="{% url 'about' %}" class="btn btn-simple">About</a>
                  <a class="nav-item nav-link" href="{% url 'companys:all' %}"class="btn btn-simple">Companies</a>
                  <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
                  <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
                {% endif %}
              </div>
            </ul>
          </div>
        </nav>
      </div>
    </header>

  </section>
  <body style="background-color: #a2d2ff;">

  <div class="card card-container" >
    <div class="card-body" style="background-color:#ffc8dd">
      {% block content %}
      <!-- This is where we will inherit our data in the page -->
    {% endblock %}    
  </div>
  </div>
  <!-- Creating a footer using Html and CSS -->
  <footer class="footer">
    <div class="container-fluid">
      <div class="container">
        <div class="footer-info">
            <h2>Developed by:</h2>
            <div class="footer-menu">
                <p>Hridyesh Bisht</p>
                <p>Kavya Suthar</p>
                <p>Sejal Srestha</p>
            </div>
        </div>
    </div>
  </footer>
</div>

<!-- API's for jquery and js files  -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js'></script>
<script src="{% static 'js/master.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends "base.html" %}
<!-- Extending base.html -->
{% block content %}
<!-- Using a card from bootstrap 4 -->
    <div class="card">
        <div class="card-body">
            <div class="information" style="padding: 10px;">
                <h1 style="text-align:center">Welcome to Resume Filter Application</h1>
                <hr>
                <br>
                <p>
                    Our ultimate motive is to provide a better solution to the current hiring process using Text and Psychological analysis of the applicant. 
                    Giving a better view of applicant’s  psychological understanding to the recruiter.
                </p>
                <ol>
                    <li>Applicants can Sign up, log in and fill the resume application form of companies.</li>
                    <li>Recruiters can further view the resume application form data and sort them according to their culture of the company.</li>
                    <li>Administrators can check the list of applicants, applicant’s forms and recruiters.</li>
                </ol>

                <p style="text-align:center;"><img src="https://michaelgomes20705.files.wordpress.com/2015/07/untitled.jpg" alt="A Resume pun pic" style="width:500px;height:300px;"></p>
                <h3> API's Used:</h3>
                <ol>
                    <li>Personality Prediction API using CatBoost Classifier algoritm and Flask</li>
                    <li>Sentiment Prediction API using Sequential Neural Network algoritm and Flask </li>
                    <!-- <li><a href="https://dandelion.eu/docs/api/datatxt/sent/v1/"></a>A third party API to predict confidence in text.</li> -->
                </ol>
                
                <h3> Future of the project:</h3>
                <h5>We could use AWS Cloud Services to further improve my application,</h5>
                <ol>
                    <li><a href="https://aws.amazon.com/s3/?nc2=h_ql_prod_st_s3">Amazon Simple Storage Service (Amazon S3) for better scalability, data availability, security, and performance.</a></li>
                    <li><a href="https://aws.amazon.com/ec2/">AWS EC2 for better computational resouces required by our API's.</a></li>
                    <li><a href="https://aws.amazon.com/sagemaker/?nc2=h_ql_prod_ml_sm">Amazon Sagemaker to better train Machine Learning Algorithms and to create end points to communicate with them.</a></li>
                </ol>
            
                <h3> Resources refered:</h3>
                <ol>
                    <li><a href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/">Official Django Documentation.</a></li>
                    <li><a href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django">Official Mozilla Documentation.</a></li>
                    <li><a href="https://jalammar.github.io/illustrated-bert/">To understand BERT</a></li>
                </ol>
                <p></p>
                </div>
                
                <p></p>        
            </div>         
        </div>
    </div>

{% endblock %}

templates/test.html
{% extends "base.html" %}
<!-- inherits from base.html file -->
{% block content %}
<div class="card">
  <div class="card-body">
      <div class="information" style="padding: 10px;">
          <h1 style="text-align:center">You are now logged in!</h1>
          <h2><a href="{% url 'companys:all'%}">Go to Companies</a></h2>
          <!-- Using url pattern to go to the correct url file of companies urls.py -->
      </div>
  </div>
</div>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
<!-- extend from base.html file -->
{% block content %}
    <!-- inherit to block content in base.html file -->
    <div class="card">
        <div class="card-body">
            <div class="information" style="padding: 10px;">
                <h1>Thanks for visiting! Come back soon!</h1>
            </div>
        </div>
      </div>

{% endblock %}