accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 

    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.SignUp.as_view(), name="signup"),
]

applications/urls.py
from django.urls import path
from . import views

app_name='applications'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.ApplicationList.as_view(), name="all"),
    path("new/", views.CreateApplication.as_view(), name="create"),
    path("by/<username>/",views.UserApplications.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.ApplicationDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeleteApplication.as_view(),name="delete"),

]

companys/urls.py
from django.urls import path
from . import views

app_name = 'companys'

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.ListCompanys.as_view(), name="all"),
    path("new/", views.CreateCompany.as_view(), name="create"),
    path("applications/in/<slug>/",views.SingleCompany.as_view(),name="single"),
    path("join/<slug>/",views.JoinCompany.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveCompany.as_view(),name="leave"),
]

resumefilter/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
 

urlpatterns = [
    # As as_view is used to display form as a view, 
    # classmethod as_view(**initkwargs)
    # Returns a callable view that takes a request and returns a response: 
    path('', views.HomePage.as_view(), name="home"),
    path('about/', views.AboutPage.as_view(), name="about"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('companys/',include("companys.urls", namespace="companys")),
    path('applications/', include("applications.urls", namespace="applications")),
]

companys/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
from accounts.models import User

# pip install misaka
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()


class Company(models.Model):
    '''
    Responsible for storing name and description of the company
    '''
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="CompanyMember")

    def __str__(self):       
        '''
        For the admin side, to unique indentify each company name        
        '''
        return self.name

    def save(self, *args, **kwargs):
        '''
        Saving the company details       
        '''
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        '''
        Unique page for details of a company
        '''
        return reverse("companys:single", kwargs={"slug": self.slug})

    class Meta:
        '''
        Sorting the companies by names        
        '''
        ordering = ["name"]


class CompanyMember(models.Model):
    '''
    Responsible for storing user and forms filled by the user for each company
    '''
    company = models.ForeignKey(Company,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_companys',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        '''
        An applicant and a company must be unique together       
        '''
        unique_together = ("company", "user")

companys/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from . models import Company,CompanyMember
from . import models

class CreateCompany(LoginRequiredMixin, generic.CreateView):
    '''
    Create a company Login is required
    '''
    fields = ("name", "description")
    model = Company

class SingleCompany(generic.DetailView):
    '''
    View details of a particular company using generic Detail view method
    '''
    model = Company

class ListCompanys(generic.ListView):
    '''
    View list of all companies using list view method
    '''
    model = Company


class JoinCompany(LoginRequiredMixin, generic.RedirectView):
    '''
    To fill the applicantion form for a company, Login is required  and redirect to confirmation of filling the form
    '''

    def get_redirect_url(self, *args, **kwargs):
        # To redirect to the particular company page
        return reverse("companys:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        # To get company form, if we can't then return a error stating you have already filled the form
        company = get_object_or_404(Company,slug=self.kwargs.get("slug"))

        try:
            CompanyMember.objects.create(user=self.request.user,company=company)

        except IntegrityError:
            messages.warning(self.request,("Warning, you have already filled the from for {}".format(company.name)))

        else:
            messages.success(self.request,"you have filled the from for {} company.".format(company.name))

        return super().get(request, *args, **kwargs)


class LeaveCompany(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # To redirect to the particular company page
        return reverse("companys:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        # To get company form, if we can't then return a error stating you have already filled the form
        try:
            membership = models.CompanyMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.CompanyMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this company because you haven't filled the form for it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully deleted the form this company."
            )
        return super().get(request, *args, **kwargs)

companys/templates/companys/company_base.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="card">
  <div class="card-body">
    <div class="container">
      <h2 class="text-center">Company page</h2>
      <hr>  
      <br>
      <div class="row">
        {% block precompany %}{% endblock %}
        {% block company_content %}{% endblock %}
        {% block postcompany %}{% endblock %}
      </div>
    </div>

  </div>
</div>  
{% endblock %}

companys/templates/companys/company_detail.html
{% extends "companys/company_base.html" %}

{% block precompany %}
<div class="container">
  <h1>{{company.name}}</h1>
  <h2> {{ company.description_html|safe }}</h2>
	<br>	
  </div>
</div>
{% endblock %}

{% block company_content %}

<div class="col-md-8">
	{% if company.applications.count == 0 %}
	<h2>No posts in this company yet!</h2>

	{% else %}
		<!-- include is similar to extend just used to extend but in middle of html file -->
		{% for application in company.applications.all %}
			{% include "applications/_application.html" %}
		{% endfor %}

	{% endif %}
	<br>
</div>
{% endblock %}

companys/templates/companys/company_form.html
{% extends "companys/company_base.html" %}
{% load bootstrap4 %}

{% block company_content %}
<div class="container">
  <h4>Create A New Group</h4>
  <form method="POST" action="{% url 'companys:create' %}" id="companyForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
    {% buttons %}
  		<button type="submit" class="btn btn-primary btn-large">Create</button>
  	{% endbuttons %}
  </form>
</div>
{% endblock %}

companys/templates/companys/company_list.html
{% extends "companys/company_base.html" %}
<!-- extends from company_base.html -->
{% block precompany %}
<!-- Inherits to precompany block in company_base.html -->
<div class="col-md-4">
	<div class="content">
		<!-- If the user is authenticated, then he will see the apply button for companies -->
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'applications:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Companies</h2>

			<p>Welcome to the Companies Page! <br>Select a Company with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<!-- Create a global application -->
	<a href="{% url 'applications:create' %}" class="btn btn-warning" role="button"><span class="fa fa-plus"></span> Apply to a New Company!</a>
	{% endif %}
	<p></p>
</div>
{% endblock %}

<!-- Displaying the list of companies -->
{% block company_content %}
<div class="col-md-8">
	<div class="list-company">
		<!-- Using SQl injection into html page -->
		{% for company in object_list %}
		<!-- For information on a particular company -->
		<a href="{% url 'companys:single' slug=company.slug %}"
		class="list-company-item list-company-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ company.name }}</h3>
			<p class="mb-1">{{ company.description_html|safe }}</p> 			
			<!-- Html code is a safe way -->
		</a>

		{% endfor %}
		<br>
	</div>
</div>
{% endblock %}